name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  tag-version:
    name: tag-version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.0.0
    - name: Get the current version
      uses: pchynoweth/action-get-npm-version@master
      id: package-version
    - name: Apply tag
      uses: pchynoweth/apply-tag-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.package-version.outputs.version }}
